version: 2

workflows:
  version: 2
  production:
    jobs:
      - lint:
          context: App
      - test:
          context: App

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.36-alpine
    steps:
      - checkout
      - run: golangci-lint run -v --timeout=5m
  test:
    docker:
      - image: golang:1.15.8-alpine3.13
      - image: mongo:3.6.22
    steps:
      - run: apk add git build-base
      - checkout
      - run: IDENTITYSERVICE_CONN_URI="mongodb://localhost:27017" IDENTITYSERVICE_DB="identityserviceTestDb" go test -v ./...
